//
//  DeveloperPreview.swift
//  Airbnb-Clone
//
//  Created by Bahittin on 20.12.2023.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()
    
    private init() {}
    
    var listings: [Listing] = [
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "John Smith",
              ownerImageUrl: "maleprofilephoto",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberofGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              tatitude: 25.7850,
              longitude: -80.1936,
              imageURLs: ["image1", "image2", "image3" ,"image4"],
              adress: "124 Main St",
              city: "Miami",
              state: "Florida",
              title: "Miami Villa",
              rating: 4.86,
              features: [.selfCheckIn, .superHost],
              ameneties: [.wifi, .alarmsystem, .balcony, .laundry, .tv],
              type: .villa
             ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "John Smith",
              ownerImageUrl: "maleprofilephoto",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberofGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              tatitude: 25.7850,
              longitude: -80.1936,
              imageURLs: ["image4", "image1", "image3" ,"image4"],
              adress: "124 Main St",
              city: "Miami",
              state: "Florida",
              title: "Miami Beach House",
              rating: 4.86,
              features: [.selfCheckIn, .superHost],
              ameneties: [.wifi, .alarmsystem, .tv, .kitchen, .office],
              type: .house
             ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Steve Johnson",
              ownerImageUrl: "maleprofilephoto",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberofGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              tatitude: 25.7650,
              longitude: -80.1936,
              imageURLs: ["image2", "image4", "image1" ,"image3"],
              adress: "124 Main St",
              city: "Miami",
              state: "Florida",
              title: "Beatiful Miami apartment in downtown Brickell",
              rating: 4.32,
              features: [.selfCheckIn, .superHost],
              ameneties: [.wifi, .alarmsystem, .balcony],
              type: .apartment
             ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Harry Styles",
              ownerImageUrl: "maleprofilephoto",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberofGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 763,
              tatitude: 34.2,
              longitude: -118.0426,
              imageURLs: ["image3", "image2", "image4" ,"image1"],
              adress: "124 Main St",
              city: "Los Angeles",
              state: "California",
              title: "Beatiful Los Angeles home in Brickell",
              rating: 4.97,
              features: [.selfCheckIn, .superHost],
              ameneties: [.wifi, .alarmsystem, .pool],
              type: .apartment
             ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Timothy Chalamet",
              ownerImageUrl: "maleprofilephoto",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberofGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 827,
              tatitude: 34.1,
              longitude: -80.1936,
              imageURLs: ["image1", "image4", "image2" ,"image3"],
              adress: "124 Main St",
              city: "Los Angeles",
              state: "California",
              title: "Beatiful Los Angeles home in the Hollywood Hills",
              rating: 4.46,
              features: [.selfCheckIn, .superHost],
              ameneties: [.wifi, .alarmsystem, .balcony],
              type: .apartment
             ),
    ]
}
